language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

install: python setup.py install

before_script: pip install -r test_requirements.txt

script:
  - py.test --cov panci
  - coveralls

